### PR TITLE
Fixes websocket reconnection logic

### PR DESCRIPTION
**Pull request by dmjio**
@FPtje can I get a review here.

Rebased your code with one additional commit to reconnect only when the socket has closed abnormally (when `CLOSED_NORMAL` is not the case). 

Note, this doesn't include client-side closing or reconnecting (just server). Handling client side socket closing / reopening goes back to managing dynamic subscriptions, which is something `miso` doesn't have at current.

### CODE REVIEW

**Comment by FPtje** [comment]
Looks good. I reckon the normal closing of a websocket is indeed the only time it shouldn't reconnect.

If you like I can run a quick test in a couple of hours.

**Comment by dmjio** [comment]
@FPtje that would be fantastic.

**Comment by FPtje** [comment]
Looks like it's still recreating the sockets. Hold on, let me see if I can do some debugging.

**Comment by FPtje** [comment]
The server isn't sending a nice close message. I'll have to postpone debugging

**Comment by FPtje** [comment]
Finally I got the server to work right. It all works properly. The server sends the close message, after which Miso closes the web socket. Miso doesn't recreate the socket.

**Comment by dmjio** [comment]
@FPtje I'd be curious to know why it wasn't working initially. `sendClose` from websockets /should/ send the correct code by default.
```haskell
sendClose :: WebSocketsData a => Connection -> a -> IO ()
sendClose conn = sendCloseCode conn 1000
```
We can merge for now and add more sophisticated reconnection logic later. Thanks again!

**Comment by FPtje** [comment]
It wasn't working initially because I didn't call `sendClose` :)

**Comment by dmjio** [comment]
:)

**Pull request merged**
