### PR TITLE
Disable GHCJS8

### PR DESCRIPTION
**Pull request by dmjio**
https://github.com/NixOS/nixpkgs/pull/22369

@peti Hello ! :)

Any ideas as to when the aforementioned [patch](https://github.com/NixOS/nixpkgs/pull/22369/commits/344227bfb9dc77e18d1789336313959df8e3e9af) will hit `nixpkgs-unstable`?

### CODE REVIEW

**Comment by peti** [comment]
Several months ago?

**Comment by dmjio** [comment]
@peti, Ah, well it seems that `haddock-api` is still trying to be built when `ghcjsHEAD` is used. Maybe this is a different, unrelated issue. https://hydra.dmj.io/build/11801/nixlog/1

```bash
➜  miso git:(disable-ghcjs8-build) nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
➜  miso git:(disable-ghcjs8-build) nix-channel --update
downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-17.09pre111456.d4ef5ac0e9/nixexprs.tar.xz’...
downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-17.09pre111456.d4ef5ac0e9/nixexprs.tar.xz’... [8364/8835 KiB, 8326.2 KiB/s]
unpacking channels...
➜  miso git:(disable-ghcjs8-build) nix-shell -p 'haskell.packages.ghcjsHEAD.ghcWithPackages (p: with p; [ aeson ])'

these derivations will be built:
  /nix/store/npjb0l65c0v817p4j04dsypf9z1nn4r2-haddock-api-2.18.1.drv
  /nix/store/q2w14i7db0frza3yv6hivhqfj6lvif3v-haddock-2.18.1.drv
  /nix/store/p4bl5b4kl0hgggsgrali8c2xsbz6wssw-ghcjs-0.2.020170323.drv
  /nix/store/qf64wh9p60gvqsm1lw3x3cjr89rd7v3v-Cabal-1.24.0.0.drv
  /nix/store/wh8dc4y850s67l48z5imw7fjdsy9cxby-hscolour-1.24.1.drv
  /nix/store/91qidm09w5jh1bq3wahy392biqlbjsp5-Cabal-1.24.0.0.drv
  /nix/store/004s7zypqz6vhd83k8g5qpbncp7xlxql-vector-0.11.0.0.drv
  /nix/store/6cd4qslkjniginc81lc3315vph6x36fw-integer-logarithms-1.0.1.drv
  /nix/store/rbinj1a2ks8mqb19jg6apycyjc8a9i1x-old-locale-1.0.0.7.drv
  /nix/store/7z3zyn80zrvwh187g8xcs6wh2139pdkf-time-locale-compat-0.1.1.3.drv
  /nix/store/b97vfpy036lz8b2dm3h1ardfcbsdjxs4-text-1.2.2.1.drv
  /nix/store/f7jjhdvssf17rlq4m8zzzcxji8ba3q8c-hashable-1.2.4.0.drv
  /nix/store/nlzdd9vl64dy2nnf8shsnl05nqxn8n20-random-1.1.drv
  /nix/store/9m5yp2bf2l0bik2sf26b0iqnm9m191yf-uuid-types-1.0.3.drv
  /nix/store/f9vgkvhq6zff8x5ihj924d7ab6jnvfcl-dlist-0.8.0.2.drv
  /nix/store/lxcfzz498nz1mwmnr35ls0l98qzpzywk-unordered-containers-0.2.7.2.drv
  /nix/store/pqzjlnb0xqaif9506i9fp0rdfp1zrsgd-scientific-0.3.4.10.drv
  /nix/store/zx98ggpa5adpaz1bskr1a9d7mc170426-transformers-compat-0.5.1.4.drv
  /nix/store/q3r5yld6fkirhrpfjq5gbgc23n3wf5cq-tagged-0.8.5.drv
  /nix/store/v9mxwai5v4v4kfbv6a22949lw42a00yg-base-compat-0.9.3.drv
  /nix/store/vybq563cl6dl71wv6b3lyd973pblgl2v-attoparsec-0.13.1.0.drv
  /nix/store/w1y5d3087x23bzcjcqn5mjx5nd6x7za5-aeson-1.1.1.0.drv
  /nix/store/6rhb1fa4qbk72lrpdcdw7rssyzmrnqgd-ghcjs-0.2.020170323-with-packages.drv
building path(s) ‘/nix/store/byzaxkdwacc2sbgihp0gynx2zbcirr5l-haddock-api-2.18.1’
setupCompilerEnvironmentPhase
Build with /nix/store/iy783h33w3grxlay4azx0snny9y351ck-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/mz6gvy41vb2xlmiwyf5zscddbldjb15f-haddock-api-2.18.1.tar.gz
source root is haddock-api-2.18.1
setting SOURCE_DATE_EPOCH to timestamp 1500540397 of file haddock-api-2.18.1/test/Spec.hs
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/var/folders/x4/92d7c1vd7wl88gdw6668rnr80000gp/T/nix-build-haddock-api-2.18.1.drv-0/package.conf.d -j8 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /private/var/folders/x4/92d7c1vd7wl88gdw6668rnr80000gp/T/nix-build-haddock-api-2.18.1.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/byzaxkdwacc2sbgihp0gynx2zbcirr5l-haddock-api-2.18.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=clang --package-db=/private/var/folders/x4/92d7c1vd7wl88gdw6668rnr80000gp/T/nix-build-haddock-api-2.18.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j8 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --extra-include-dirs=/nix/store/b6ll5iicpyags3j9akx25bynm2hqr9sj-libc++-4.0.1/include --extra-lib-dirs=/nix/store/b6ll5iicpyags3j9akx25bynm2hqr9sj-libc++-4.0.1/lib
Setup: haddock-api.cabal: This package requires at least Cabal version 2.0
builder for ‘/nix/store/npjb0l65c0v817p4j04dsypf9z1nn4r2-haddock-api-2.18.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/p4bl5b4kl0hgggsgrali8c2xsbz6wssw-ghcjs-0.2.020170323.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6rhb1fa4qbk72lrpdcdw7rssyzmrnqgd-ghcjs-0.2.020170323-with-packages.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/6rhb1fa4qbk72lrpdcdw7rssyzmrnqgd-ghcjs-0.2.020170323-with-packages.drv’ failed
/Users/david/.nix-profile/bin/nix-shell: failed to build all dependencies
```

**Comment by cocreature** [comment]
It looks like in `nixpkgs` HEAD `haddock-api` refers to `2.17.4` again so hopefully `unstable` will soon be fixed.

**Comment by dmjio** [comment]
@cocreature, ah thanks.

**Comment by dmjio** [comment]
Forking our own nixpkgs, and maintaining ghcjs until our patches are merged upstream.

**Pull request closed without merging**
